name: Flutter Build APK (ZIP SAFE)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Extract ZIP
        run: |
          unzip *.zip
          rm *.zip

      - name: Find pubspec.yaml
        run: |
          echo "SEARCH pubspec.yaml"
          find . -name pubspec.yaml

      - name: Enter Flutter Project Folder
        run: |
          DIR=$(find . -name pubspec.yaml | head -n 1 | xargs dirname)
          echo "PROJECT DIR: $DIR"
          echo "PROJECT_DIR=$DIR" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter Pub Get
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: Build APK (Release)
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: |
            **/build/app/outputs/flutter-apk/*.apk
