name: Flutter Build APK (AUTO DETECT)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Find Flutter project
        run: |
          echo "Searching pubspec.yaml..."
          find . -name pubspec.yaml

      - name: Set project directory
        run: |
          DIR=$(find . -name pubspec.yaml | head -n 1 | xargs dirname)
          echo "PROJECT_DIR=$DIR" >> $GITHUB_ENV
          echo "Flutter project at: $DIR"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter Pub Get
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: Build APK Release
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: |
            **/build/app/outputs/flutter-apk/*.apk
